name: post-varloc-data-pipeline
channels:
  - conda-forge
  - bioconda
dependencies:
  # - python=3.10
  - black
  - flake8
  - isort
  - pytest
  - pip
  - pandas
  - typer
  - loguru
  - tqdm
  - ipython
  - scikit-learn
  - xarray
  - openpyxl
  - zarr
  - dask
  - pyyaml
  - vembrane=2.1.0

  # removed forever
  #  - jupyterlab
  #  - matplotlib
  #  - notebook


  - pip:
    - python-dotenv
    - mkdocs
    - -e .
