name: post-varloc-data-pipeline
channels:
  - conda-forge
  - bioconda
dependencies:
  # - python=3.10
  - black
  - flake8
  - isort
  - pip
  - pandas
  - typer
  - loguru
  - tqdm
  - ipython
  - scikit-learn
  - xarray
  - openpyxl
  - zarr
  - vembrane=2.1.0

  # removed forever
  #  - jupyterlab
#  - matplotlib
#  - notebook
  # - zarr
  # - dask

  - pip:
    - python-dotenv
    - mkdocs
    - -e .
